class Day7Suite extends munit.FunSuite {
    val initialDiagram = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............""".split("\n").toList

    test("manifoldDiagram") { 
        val expectedDiagram = """.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
....|.|.|.|....
...|^|^|||^|...
...|.|.|||.|...
..|^|^|||^|^|..
..|.|.|||.|.|..
.|^|||^||.||^|.
.|.|||.||.||.|.
|^|^|^|^|^|||^|
|.|.|.|.|.|||.|""".split("\n").toList
        val splits = List(0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 4, 0, 3, 0, 5, 0)
        assertEquals(manifoldDiagram(initialDiagram), expectedDiagram.zip(splits))
    }

    test("numPathsToPoint") {
        val pathsToPoint = numPathsToPoint(initialDiagram)
        assertEquals(pathsToPoint.last.sum, 40L)
    }
}